--------------------------------------------------

USE scada_historian;
select * from SensorReadings order by Timestamp;
select * from OutageLog;
select * from SyncState;
select * from RecoveryAudit;
select * from SyncLog;

--------------------------------------------------
-- USE master;
-- DROP DATABASE scada_historian;
use scada_historian;
DROP TABLE IF EXISTS SensorReadings;
DROP TABLE IF EXISTS OutageLog;
DROP TABLE IF EXISTS SyncLog;
DROP TABLE IF EXISTS SyncState;
DROP TABLE IF EXISTS RecoveryAudit;

-- =====================================================
-- DATABASE: scada_historian  (Version 3)
-- Run on BOTH instances
-- =====================================================
USE master;
GO
DROP DATABASE IF EXISTS scada_historian;
GO
CREATE DATABASE scada_historian;
GO
USE scada_historian;
GO

-- -----------------------------------------------------
-- 1. Main sensor data table (simulator writes here)
-- -----------------------------------------------------
CREATE TABLE SensorReadings (
    RowGUID CHAR(36) PRIMARY KEY,
    SensorTimestamp DATETIME2 NOT NULL,   -- time when the row was dumped (set by simulator)
    TagID INT NOT NULL,
    SensorDate DATETIME2 NOT NULL,        -- random date generated by simulator (sensor's original timestamp)
    Value FLOAT NOT NULL,
    Quality VARCHAR(20) DEFAULT 'Good'
);
GO

-- -----------------------------------------------------
-- 2. Outage event log (records every offline/online transition)
-- -----------------------------------------------------
CREATE TABLE OutageLog (
    OutageID INT IDENTITY PRIMARY KEY,
    ServerName VARCHAR(50) NOT NULL,      -- 'PRIMARY' or 'SECONDARY'
    ServerEvents VARCHAR(50) NOT NULL,    -- 'offline' or 'online'
    EventDateTime DATETIME2 NULL,         -- when the event was detected
    SyncStatus VARCHAR(20) DEFAULT 'Pending',
    Notes VARCHAR(500) NULL
);
GO

-- -----------------------------------------------------
-- 3. Sync audit table (stores rows missed by remote server)
-- -----------------------------------------------------
CREATE TABLE SyncRecordsStatus (
    RowGUID CHAR(36) PRIMARY KEY,
    SensorTimestamp DATETIME2 NOT NULL,
    TagID INT NOT NULL,
    SensorDate DATETIME2 NOT NULL,
    Value FLOAT NOT NULL,
    Quality VARCHAR(20) DEFAULT 'Good',
    SyncSuccess BIT DEFAULT 0             -- 0 = not yet synced to remote, 1 = synced
);
GO

-- -----------------------------------------------------

use scada_historian;
DROP TABLE IF EXISTS SensorReadings;
DROP TABLE IF EXISTS OutageLog;
DROP TABLE IF EXISTS SyncRecordsStatus;

use scada_historian;
select * from SensorReadings order by SensorTimestamp;
select * from OutageLog;
select * from SyncRecordsStatus order by SensorTimestamp;
